### ISSUE TITLE
Motors "jolt" and stop moving for a short time (1/4 to 1/2 a second)

### ISSUE THREAD

**Issue by breathlessblizzard** [WarriorRobots/deepspace-season#1]
Potential problem:

Every talon on the robot will momentarily blink yellow and all motors will suddenly stop turning for an instant, before returning to normal motion. If the robot is on blocks, it sounds like a "THUNK" and shakes the robot a little.

Hypotheses as to why it happened: (doing these fixed it the first time)
- USB printer cable is faulty or not plugged in correctly
- Roborio needs to be restarted

First encountered:
January 25th 2019, on deepspace practice robot with loose electronics

**Comment by WestwoodRobots** [comment]
Hypothesis:
The intermittent disconnecting is caused by high CPU usage on the drive computer, usually from running too many programs like Chrome and Shuffleboard. A possible solution is to restart the computer and make sure extra programs aren't opening at startup.
