### ISSUE TITLE
Fix elevator math

### ISSUE THREAD

**Issue by dogpetkid** [WarriorRobots/deepspace-season#16]
The math that is applied to the delta command of the elevator is incorrect, it has a proportional error which leads Saxon to believe there is a conversion error. The easiest solution may be to remove extra conversions and use `initial encoder clicks + clicks per inch * inches desired for delta = intended encoder clicks`.

**Comment by WestwoodRobots** [comment]
No issues have been found in practice since AZ North but the math has still not been checked.

**Comment by dogpetkid** [comment]
From yesterday during the competition, we noticed that the math on the competition elevator still appears to be off. Going over the math should be something that must be done before Huston.

**Comment by breathlessblizzard** [comment]
Important task for today: Measure the elevator and record height vs encoder
clicks. We will compare it with the practice robot at home.

**Comment by breathlessblizzard** [comment]
Update: We suspect that the competition robot has an 18-tooth sprocket installed instead of a 16-tooth. This would explain the cumulative error.

**Comment by WestwoodRobots** [comment]
This is not able to be confirmed so this commit must stay open.

**Comment by dogpetkid** [comment]
The elevator math is still not fixed and this is not going to be resolved because only the COMP robot is being used and values are being tuned for it alone.
