### ISSUE TITLE
Calling unsafety-ed code

### ISSUE THREAD

**Issue by dogpetkid** [WarriorRobots/deepspace-season#20]
Inside of [ElevatorSubsystem](https://github.com/WarriorRobots/deepspace-season/blob/59ae7de948580342a7cc17b5fd358ce6bbafd111/src/main/java/frc/robot/subsystems/ElevatorSubsystem.java) there is a the same code within two different functions however one does not have the safety on it. It may be best to depricate this unsafe version.
Function with safety:
```
public void moveElevatorTo(double inches) {
		// Safety is removed in this code snipping
		winch.set(ControlMode.Position, toClicks(inches));
}
```
Function without safety:
```
public void stabilizeElevator(double inches) {
		winch.set(ControlMode.Position, toClicks(inches));
}
```

**Comment by breathlessblizzard** [comment]
Not actually an issue; explained in last commit

**Comment by WestwoodRobots** [comment]
The commit referenced is 7c616ad52b476cdf0491202d58ed142965fc1753.
