### ISSUE TITLE
LED blinking for Cargo

### ISSUE THREAD

**Issue by WestwoodRobots** [WarriorRobots/deepspace-season#24]
When putting in cargo into the cargo bay, the LED strip could be turned off and then blinked when the robot is within 4 inches of the cargo bay. This could be measured by using a infrared sensor to tuned to 4 inches from the face of the cargo ship. This would require an LED controller as well.

**Comment by dogpetkid** [comment]
This enhancement is completed in a9000be and uses the REV BLINKIN.
