### ISSUE TITLE
Disconnecting from robot radio soft-locks Limelight camera

### ISSUE THREAD

**Issue by WestwoodRobots** [WarriorRobots/deepspace-season#4]
Background knowledge needed:
The Limelight 2 has two LED indicators on its top. The green LED blinks slowly when there is no target acquired, and blinks rapidly when there is a target. The yellow LED blinks steadily when the Limelight is set to a dynamic IP, and is solid when the Limelight has a static IP.

Problem:
On robot startup, both LEDs act normally. If a computer connects, then disconnects, from the robot, the LEDs will freeze and the camera will become unresponsive, even to the RESET button. Reconnecting with the same computer will resume the camera's operations, but connecting with a different computer will soft-lock the camera until the robot power cycles.

Encountered:
First week of February, starting 1/31 to 2/2

Workaround:
Power cycle the robot *every time* we switch computers (for example, to access <limelight.local:5801>).

**Comment by breathlessblizzard** [comment]
This issue has not been observed for a number of weeks, and the camera has been updated at least once since this was written. @dogpetkid should we close this?
